name: 'CD Pipeline'

on:
  pull_request: 
    types:
      - closed
    branches:
      - main
    paths:
      - 'src/**'
      
      
jobs:
  
  build:
    name: 'Release Spreadsheet Extractor'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/src
    
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
      
      - name: 'Setup Python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: 'Install dependencies'
        run: |
          pip install poetry
          poetry install --no-interaction --no-root
      
      - name: Build distribution
        id: build_distribution
        run: |
          poetry build --no-interaction
          echo "PACKAGE_VERSION=$(poetry version --no-interaction -s)" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$(poetry version --no-interaction)" >> $GITHUB_ENV
      
      - name: 'Create if: github.event.pull_request.merged == true release'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.PACKAGE_NAME }}
          tag_name: 'spreadsheet_extractor_v${{ env.PACKAGE_VERSION }}'
          generate_release_notes: true
          files: |
            ${{ github.workspace }}/src/dist/**

      - name: 'Publish release'
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
      