name: 'CI Pipeline'

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
    paths:
      - 'src/**'

jobs:

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
      - name: 'Setup Python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: 'Install test dependencies'
        run: |
          pip install pytest poetry
          pip list
      - name: 'Install dependencies'
        id: install_dependencies
        working-directory: ${{ github.workspace }}/src
        run: |
          poetry install --no-interaction --no-root
          poetry show --no-interaction
      - name: 'Run tests'
        id: run_tests
        if: steps.install_dependencies.outcome == 'success'
        working-directory: ${{ github.workspace }}/src/tests
        env:
          DATA_PATH: "${{ github.workspace }}/src/tests/assets"
          SPREADSHEET_EXTRACTOR_CONFIG_PATH: "${{ github.workspace }}/src/tests/assets/sources"
        run: |
          poetry run --no-interaction pytest --junit-xml pytest_.xml
      - name: 'Publish tests results'
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "${{ github.workspace }}/src/tests/pytest_.xml"