name: 'CI Pipeline'

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
    paths:
      - 'src/**'

jobs:

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v4
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install OS dependencies'
        run: |
          RUN apt-get -y update && apt-get -y upgrade \
          && apt-get -y install \
              software-properties-common \
              libffi-dev \
              libpq-dev\
              gcc
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: 'Install dependencies'
        id: install_dependencies
        working-directory: ${{ github.workspace }}/src
        run: |
          uv sync
      - name: 'Run tests'
        id: run_tests
        if: steps.install_dependencies.outcome == 'success'
        working-directory: ${{ github.workspace }}/src/tests
        env:
          DATA_PATH: "${{ github.workspace }}/src/tests/assets"
          SPREADSHEET_EXTRACTOR_CONFIG_PATH: "${{ github.workspace }}/src/tests/assets/sources"
        run: |
          uv run --no-interaction pytest --junit-xml pytest_.xml
      - name: 'Publish tests results'
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "${{ github.workspace }}/src/tests/pytest_.xml"